name: Fork Sync via GitHub App

on:
  workflow_call:
    inputs:
      original_repo:
        required: true
        type: string
      upstream_branch:
        required: true
        type: string
      fork_branch:
        required: true
        type: string

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout fork repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0

      - name: Add upstream remote
        run: git remote add upstream https://github.com/${{ inputs.original_repo }}.git

      - name: Fetch upstream changes
        run: git fetch upstream ${{ inputs.upstream_branch }}

      - name: Create sync branch
        run: |
          git checkout -B fork-sync-temp upstream/${{ inputs.upstream_branch }}
          git push -f origin fork-sync-temp

      - name: Create Pull Request to sync fork
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: "🔄 Sync fork with upstream"
          title: "🔄 Sync fork with upstream"
          body: |
            This pull request was automatically generated by a bot to keep this fork up to date with upstream changes.
          base: ${{ inputs.fork_branch }}
          head: fork-sync-temp
