# common-actions/.github/workflows/trigger-fork-sync-v2.yml

name: Trigger Fork Sync V2

on:
  workflow_call:
    inputs:
      fork_repo:
        required: true
        type: string
      branch:
        required: true
        type: string
    secrets:
      PAT:
        required: true

jobs:
  trigger-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to fork
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ inputs.fork_repo }}
          event-type: sync-from-upstream
          client-payload: |
            {
              "branch": "${{ inputs.branch }}"
            }
