# common-actions/.github/workflows/trigger-fork-sync.yml

name: Trigger Fork Sync V2

on:
  workflow_call:
    inputs:
      source_repo:
        required: true
        type: string
      source_branch:
        required: true
        type: string
      fork_repo:
        required: true
        type: string
      target_branch:
        required: true
        type: string
    secrets:
      PAT:
        required: true

jobs:
  trigger-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch on fork
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ inputs.fork_repo }}
          event-type: sync-from-upstream
          client-payload: |
            {
              "source_repo": "${{ inputs.source_repo }}",
              "source_branch": "${{ inputs.source_branch }}",
              "target_branch": "${{ inputs.target_branch }}"
            }
